name = "dozo-updates-worker"
main = "worker.js"
compatibility_date = "2024-11-04"

routes = [
  { pattern = "updates.rockstage.mx/*", zone_name = "rockstage.mx" }
]

[vars]
BUCKET_NAME = "dozo-updates"

[[r2_buckets]]
binding = "DOZO_BUCKET"
bucket_name = "dozo-updates"

